### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by minarc**
Translated to korean more naturally.

### CODE REVIEW

**Comment by mna** [comment]
Hello!

Thank you so much for this! There's no way for me to judge but I think it'd make sense to ask the original person that contributed the translation, @lionking6792 if you can take a look and are happy with it, then that's good for me!

Thanks,
Martin

**Comment by mna** [comment]
Just a note to say that if we don't hear from @lionking6792 for a few more days, I'll go ahead and merge this. Feel free to ping me at the beginning of next week if I seem to have forgotten about it :) Otherwise I will likely merge it this weekend or early next week.

**Comment by mowinckel** [comment]
I'm not blaming @lionking6792 but it seems like he just used google translator or something. The Korean document is still weird. I would to advance Korean document in future.

**Comment by mowinckel** [comment]
Translated more strange sentences. Hope this document be helpful for Koreans... someday.

**Pull request merged**
