### PR TITLE
Support base tags for URL prefix

### PR DESCRIPTION
**Pull request by juliend2**
I guess it's not bullet-proof, so please let me know if you would have done it differently.
Also, since I'm new to Go, I'm not sure how to run your tests. I didn't see any Makefile or script to run them.

Please let me know! Thanks!

### CODE REVIEW

**Comment by juliend2** [comment]
related issue: https://github.com/PuerkitoBio/gocrawl/issues/45

**Comment by PuerkitoBio** [comment]
Hi Julien,

This looks ok but I'd like to see some tests for this. The table-driven tests I have implemented for gocrawl are quite complex and over-the-top, you can just write a separate, isolated `TestBaseTag(t *testing.T) {...}` function or something like that, no need to integrate into the existing tests. If you have trouble setting stuff up with file-based HTML documents, I can implement those a bit later this week.

You don't need Makefiles in go, there's a built-in test runner that can be executed with `go test`.

Thanks for the PR!
Martin

**Comment by juliend2** [comment]
Thanks for this Martin.

I think I'm missing something, because I tried to run `go test` on your master branch, and it seems to fail: https://gist.github.com/juliend2/09dc0a76306e2a706218

Are these tests passing on your side?

Thanks!
Julien

**Comment by juliend2** [comment]
Ah ok, I got it. I'll just run `go test -run TestBaseTag`. 

I'll get back to you with this test. Thanks!

**Comment by PuerkitoBio** [comment]
Hey Julien,

Sorry I've been quite busy today, but yeah I do get the failure too, I'll
have to look at that. Running your specific test is fine for the pr.

Thanks,
Martin

**Comment by juliend2** [comment]
There you go: run `go test -run BaseTag -v` to see how the new tests are passing.

As you can see in the latest commit, I had to create a [package](https://github.com/statusmachine/urlidentification) specifically designed to detect the type of URL formatting, to properly handle some kinds of values we might encounter in `a[href]` attributes.

Please let me know if you see anything you'd like me to adapt in this PR!

Regards,
Julien

**Comment by PuerkitoBio** [comment]
Hey Julien, thanks for the PR.

In handleBaseTag, you shouldn't need all the manual concatenation, there's a method `*net/url.URL.Parse()` that takes care of resolving an URL reference for you in the context of the parent URL. I believe the `base` meta tag should be resolved in the context of the document's URL, and then the URLs to enqueue should be resolved in the context of that fully resolved `base` URL (if there's a base tag, of course).

I think that should take care of the correct resolution, without requiring a new package dependency.

Thanks,
Martin

**Comment by PuerkitoBio** [comment]
Actually, you do need to concatenate the base with the url, but I think something like that would work, without needing a new package dependency: http://play.golang.org/p/gqRMxMYiPQ

I'm not quite sure how it is supposed to handle a `base` that has a `/sub/index.html` path, my guess is that it's treated just like any path, but I haven't read the details about that.

**Comment by juliend2** [comment]
According to the [specification](http://www.w3.org/TR/html5/document-metadata#the-base-element) (see the example), if the `base[href]` is `http://www.example.com/news/index.html` , and the `a[href]` is `archives.html`, then it would link to `http://www.example.com/news/archives.html`.

I'll take a look at your example code and see if I can adapt it to match the `base` tag's spec.

Thank you!

**Comment by juliend2** [comment]
I admit I didn't think about the case where someone would have another domain name than the one where the current page is hosted.

But I did some manual testing on my side (using Google Chrome and a few test sites I had), and the output of your play snippet should look like [this](https://gist.github.com/juliend2/9a6abfd3e92b084bd86f) instead.

I will see how I could modify your code (ideally), or my library, if needed, to match this desired behaviour.

Thanks for your patience. (I don't have much time these days)

**Comment by juliend2** [comment]
@PuerkitoBio , please see my latest commit.

I used your solution, but added a check for the `a[href]` to make sure it doesn't start with a `/`, before concatenating it with the `base[href]`.

All my tests are passing. Please let me know if you see anything else to change.

Thanks!

**Comment by PuerkitoBio** [comment]
Not entirely sure what the correct behaviour of base is, but that looks good (better than ignoring base for sure).

**Comment by juliend2** [comment]
Thanks!

**Pull request merged**
