### PR TITLE
Preserves source URLs upon redirects.

### LINKED ISSUE #55: redirects don't have a SourceURL value
I ran into a scenario where http://foobar.com does a 301 to https://foobar.com. The default flags normalize to http which is fine for urls that are the same content (not redirects), so I didn't want to turn off that normalization flag. Instead I was going to check the scheme/path/host of the source url to the current url in Filter. The issue is https://foobar.com does not have a source url of http://foobar.com which to me seems like it should. 

is there another preferred way to do what I'm checking that I'm not thinking of?

### PR DESCRIPTION
**Pull request by tmatsuo**
Fixes #55

### CODE REVIEW

**Comment by tmatsuo** [comment]
Oh wait, we don't need some local variables. I'll change them

**Comment by tmatsuo** [comment]
Alright, please take a look @PuerkitoBio

**Comment by tmatsuo** [comment]
Ping

**Comment by PuerkitoBio** [comment]
Yep will give it a look, was a holiday here, didn't have much time for this.

**Comment by PuerkitoBio** [comment]
Added tests and fixed a couple issues with the cloned URL context, if you can take a look before I merge, @tmatsuo (/cc @jhorwit2). It's in branch tmatsuo-add-source-upon-redirect.

**Comment by tmatsuo** [comment]
@PuerkitoBio Thanks! I looked at the changes you made and it LGTM :)

**Comment by PuerkitoBio** [comment]
Merged, thanks for the PR!

**Pull request merged**
